<?php
//database credit: https://ebookbible.org/
$book_passage = array(
  array('bible_number' => '1','short' => 'Ge','fullname' => 'Genesis','title' => 'The First Book of Moses, called Genesis','chapters' => '50'),
  array('bible_number' => '2','short' => 'Ex','fullname' => 'Exodus','title' => 'The Second Book of Moses, called Exodus','chapters' => '40'),
  array('bible_number' => '3','short' => 'Le','fullname' => 'Leviticus','title' => 'The Third Book of Moses, called Leviticus','chapters' => '27'),
  array('bible_number' => '4','short' => 'Nu','fullname' => 'Numbers','title' => 'The Fourth Book of Moses, called Numbers','chapters' => '36'),
  array('bible_number' => '5','short' => 'De','fullname' => 'Deuteronomy','title' => 'The Fifth Book of Moses, called Deuteronomy','chapters' => '34'),
  array('bible_number' => '6','short' => 'Jos','fullname' => 'Joshua','title' => 'The Book of Joshua','chapters' => '24'),
  array('bible_number' => '7','short' => 'Jg','fullname' => 'Judges','title' => 'The Book of Judges','chapters' => '21'),
  array('bible_number' => '8','short' => 'Ru','fullname' => 'Ruth','title' => 'The Book of Ruth','chapters' => '4'),
  array('bible_number' => '9','short' => '1Sa','fullname' => '1 Samuel','title' => 'The First Book of Samuel, otherwise called the First Book of the Kings','chapters' => '31'),
  array('bible_number' => '10','short' => '2Sa','fullname' => '2 Samuel','title' => 'The Second Book of Samuel, otherwise called the Second Book of the Kings','chapters' => '24'),
  array('bible_number' => '11','short' => '1Ki','fullname' => '1 Kings','title' => 'The First Book of the Kings, commonly called the Third Book of the Kings','chapters' => '22'),
  array('bible_number' => '12','short' => '2Ki','fullname' => '2 Kings','title' => 'The Second Book of the Kings, commonly called the Fourth Book of the Kings','chapters' => '25'),
  array('bible_number' => '13','short' => '1Ch','fullname' => '1 Chronicles','title' => 'The First Book of the Chronicles','chapters' => '29'),
  array('bible_number' => '14','short' => '2Ch','fullname' => '2 Chronicles','title' => 'The Second Book of the Chronicles','chapters' => '36'),
  array('bible_number' => '15','short' => 'Ezr','fullname' => 'Ezra','title' => 'Ezra','chapters' => '10'),
  array('bible_number' => '16','short' => 'Ne','fullname' => 'Nehemiah','title' => 'The Book of Nehemiah','chapters' => '13'),
  array('bible_number' => '17','short' => 'Es','fullname' => 'Esther','title' => 'The Book of Esther','chapters' => '10'),
  array('bible_number' => '18','short' => 'Job','fullname' => 'Job','title' => 'The Book of Job','chapters' => '42'),
  array('bible_number' => '19','short' => 'Ps','fullname' => 'Psalms','title' => 'The Book of Psalms','chapters' => '150'),
  array('bible_number' => '20','short' => 'Pr','fullname' => 'Proverbs','title' => 'The Proverbs','chapters' => '31'),
  array('bible_number' => '21','short' => 'Ec','fullname' => 'Ecclesiastes','title' => 'Ecclesiastes, or, The Preacher','chapters' => '12'),
  array('bible_number' => '22','short' => 'Song','fullname' => 'Song of Solomon','title' => 'The Song of Solomon','chapters' => '8'),
  array('bible_number' => '23','short' => 'Isa','fullname' => 'Isaiah','title' => 'The Book of the Prophet Isaiah','chapters' => '66'),
  array('bible_number' => '24','short' => 'Jer','fullname' => 'Jeremiah','title' => 'The Book of the Prophet Jeremiah','chapters' => '52'),
  array('bible_number' => '25','short' => 'La','fullname' => 'Lamentations','title' => 'The Lamentations of Jeremiah','chapters' => '5'),
  array('bible_number' => '26','short' => 'Eze','fullname' => 'Ezekiel','title' => 'The Book of the Prophet Ezekiel','chapters' => '48'),
  array('bible_number' => '27','short' => 'Da','fullname' => 'Daniel','title' => 'The Book of Daniel','chapters' => '12'),
  array('bible_number' => '28','short' => 'Ho','fullname' => 'Hosea','title' => 'Hosea','chapters' => '14'),
  array('bible_number' => '29','short' => 'Joe','fullname' => 'Joel','title' => 'Joel','chapters' => '3'),
  array('bible_number' => '30','short' => 'Am','fullname' => 'Amos','title' => 'Amos','chapters' => '9'),
  array('bible_number' => '31','short' => 'Ob','fullname' => 'Obadiah','title' => 'Obadiah','chapters' => '1'),
  array('bible_number' => '32','short' => 'Jon','fullname' => 'Jonah','title' => 'Jonah','chapters' => '4'),
  array('bible_number' => '33','short' => 'Mic','fullname' => 'Micah','title' => 'Micah','chapters' => '7'),
  array('bible_number' => '34','short' => 'Na','fullname' => 'Nahum','title' => 'Nahum','chapters' => '3'),
  array('bible_number' => '35','short' => 'Hab','fullname' => 'Habakkuk','title' => 'Habakkuk','chapters' => '3'),
  array('bible_number' => '36','short' => 'Zep','fullname' => 'Zephaniah','title' => 'Zephaniah','chapters' => '3'),
  array('bible_number' => '37','short' => 'Hag','fullname' => 'Haggai','title' => 'Haggai','chapters' => '2'),
  array('bible_number' => '38','short' => 'Zec','fullname' => 'Zechariah','title' => 'Zechariah','chapters' => '14'),
  array('bible_number' => '39','short' => 'Mal','fullname' => 'Malachi','title' => 'Malachi','chapters' => '4'),
  array('bible_number' => '40','short' => 'Mt','fullname' => 'Matthew','title' => 'The Gospel According to St. Matthew','chapters' => '28'),
  array('bible_number' => '41','short' => 'Mr','fullname' => 'Mark','title' => 'The Gospel According to St. Mark','chapters' => '16'),
  array('bible_number' => '42','short' => 'Lu','fullname' => 'Luke','title' => 'The Gospel According to St. Luke','chapters' => '24'),
  array('bible_number' => '43','short' => 'Joh','fullname' => 'John','title' => 'The Gospel According to St. John','chapters' => '21'),
  array('bible_number' => '44','short' => 'Ac','fullname' => 'Acts','title' => 'The Acts of the Apostles','chapters' => '28'),
  array('bible_number' => '45','short' => 'Ro','fullname' => 'Romans','title' => 'The Epistle of Paul the Apostle to the Romans','chapters' => '16'),
  array('bible_number' => '46','short' => '1Co','fullname' => '1 Corinthians','title' => 'The First Epistle of Paul the Apostle to the Corinthians','chapters' => '16'),
  array('bible_number' => '47','short' => '2Co','fullname' => '2 Corinthians','title' => 'The Second Epistle of Paul the Apostle to the Corinthians','chapters' => '13'),
  array('bible_number' => '48','short' => 'Ga','fullname' => 'Galatians','title' => 'The Epistle of Paul the Apostle to the Galatians','chapters' => '6'),
  array('bible_number' => '49','short' => 'Eph','fullname' => 'Ephesians','title' => 'The Epistle of Paul the Apostle to the Ephesians','chapters' => '6'),
  array('bible_number' => '50','short' => 'Php','fullname' => 'Philippians','title' => 'The Epistle of Paul the Apostle to the Philippians','chapters' => '4'),
  array('bible_number' => '51','short' => 'Col','fullname' => 'Colossians','title' => 'The Epistle of Paul the Apostle to the Colossians','chapters' => '4'),
  array('bible_number' => '52','short' => '1Th','fullname' => '1 Thessalonians','title' => 'The First Epistle of Paul the Apostle to the Thessalonians','chapters' => '5'),
  array('bible_number' => '53','short' => '2Th','fullname' => '2 Thessalonians','title' => 'The Second Epistle of Paul the Apostle to the Thessalonians','chapters' => '3'),
  array('bible_number' => '54','short' => '1Ti','fullname' => '1 Timothy','title' => 'The First Epistle of Paul the Apostle to Timothy','chapters' => '6'),
  array('bible_number' => '55','short' => '2Ti','fullname' => '2 Timothy','title' => 'The Second Epistle of Paul the Apostle to Timothy','chapters' => '4'),
  array('bible_number' => '56','short' => 'Tit','fullname' => 'Titus','title' => 'The Epistle of Paul to Titus','chapters' => '3'),
  array('bible_number' => '57','short' => 'Phm','fullname' => 'Philemon','title' => 'The Epistle of Paul to Philemon','chapters' => '1'),
  array('bible_number' => '58','short' => 'Heb','fullname' => 'Hebrews','title' => 'The Epistle of Paul the Apostle to the Hebrews','chapters' => '13'),
  array('bible_number' => '59','short' => 'Jas','fullname' => 'James','title' => 'The General Epistle of James','chapters' => '5'),
  array('bible_number' => '60','short' => '1Pe','fullname' => '1 Peter','title' => 'The First Epistle General of Peter','chapters' => '5'),
  array('bible_number' => '61','short' => '2Pe','fullname' => '2 Peter','title' => 'The Second Epistle General of Peter','chapters' => '3'),
  array('bible_number' => '62','short' => '1Jo','fullname' => '1 John','title' => 'The First Epistle General of John','chapters' => '5'),
  array('bible_number' => '63','short' => '2Jo','fullname' => '2 John','title' => 'The Second Epistle of John','chapters' => '1'),
  array('bible_number' => '64','short' => '3Jo','fullname' => '3 John','title' => 'The Third Epistle of John','chapters' => '1'),
  array('bible_number' => '65','short' => 'Jude','fullname' => 'Jude','title' => 'The General Epistle of Jude','chapters' => '1'),
  array('bible_number' => '66','short' => 'Re','fullname' => 'Revelation','title' => 'The Revelation of St. John the Divine','chapters' => '22')
);